In [3]:
m = [1,2,3]

In [4]:
import numpy as np

In [5]:
arr = np.array(m)

In [6]:
arr

array([1, 2, 3])

In [7]:
mm = [[1,2,3],[2,3,4]] # two dimensional array

In [8]:
np.array(mm) # if there is 2 square bracket continuously then it is 2 dimensional array

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
np.arange(0,11) #same as range function in the list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [14]:
np.zeros((5,5))  

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [16]:
np.zeros((2,4))  # here 2 represent number of rows and 4 represent number of column.

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [17]:
np.ones(3)

array([ 1.,  1.,  1.])

In [18]:
np.ones((1,5))

array([[ 1.,  1.,  1.,  1.,  1.]])

In [19]:
# linspace return evenly spaced numbers over a specified interval
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

the first argument is the starting point and second argument is ending point and third argument is the evenly distributed number of items between starting point and ending point as shown in the example.

In [21]:
np.linspace(0,50,20)

array([  0.        ,   2.63157895,   5.26315789,   7.89473684,
        10.52631579,  13.15789474,  15.78947368,  18.42105263,
        21.05263158,  23.68421053,  26.31578947,  28.94736842,
        31.57894737,  34.21052632,  36.84210526,  39.47368421,
        42.10526316,  44.73684211,  47.36842105,  50.        ])

In [23]:
np.eye(4)  # this is used to create identity matrix and the argument defines the number of rows in equal to number of coloum.

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [24]:
np.random.rand(5)  # it creates a random sample pf uniform distribution from 0 to 1.

array([ 0.0881052 ,  0.34807413,  0.22035821,  0.29125938,  0.02013709])

In [25]:
np.random.rand(5,5)

array([[ 0.87516823,  0.20123005,  0.55366314,  0.2485663 ,  0.23863694],
       [ 0.31596144,  0.28784504,  0.57506354,  0.75016177,  0.25527169],
       [ 0.67651705,  0.94319069,  0.08677512,  0.30206327,  0.53882212],
       [ 0.2384269 ,  0.4937414 ,  0.65305724,  0.43854213,  0.55939205],
       [ 0.88338161,  0.06455561,  0.78100944,  0.38860804,  0.17292581]])

In [26]:
np.random.randn(2) # it returns normal distribution instead of uniform distribution

array([-0.95917528, -0.89719444])

In [27]:
np.random.randn(4,4)

array([[-1.57984128,  0.98833984, -0.18099273, -0.67950967],
       [ 1.38422636, -0.45425515,  0.76832148, -0.30446122],
       [-0.2905224 , -1.39303058, -0.25062941,  1.348702  ],
       [ 1.42724422, -0.37442758, -0.08825062,  0.17446287]])

In [28]:
np.random.randint(1,100) 

84

the first argument is the starting point nd second is ending point and third is for number of random numbers though its not necessary as by default it is 1 

In [29]:
np.random.randint(100,1000,5)

array([317, 936, 413, 860, 544])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([27, 13,  3, 37, 31, 23, 46, 26, 18, 10])

In [35]:
arr.reshape(5,5) #it is used to converting a matrix to another matrix like one dimen to two dimen

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

not enough element to insert in the array

In [37]:
ranarr

array([27, 13,  3, 37, 31, 23, 46, 26, 18, 10])

In [38]:
ranarr.max()

46

In [39]:
ranarr.min()

3

In [40]:
ranarr.argmax() # index of the maximun value

6

In [41]:
ranarr.argmin() # index of the minimum value

2

In [43]:
arr.shape

(25,)

here it represent one dimentional vector

In [44]:
arr = arr.reshape(5,5)

In [45]:
arr.shape

(5, 5)

this represent the two dimensional arr

In [46]:
arr.dtype

dtype('int32')

this means data type is integer 32 bit

        NUMPY INDEXING AND SELECTION

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr[8] #this is called indexing

8

In [50]:
arr[1:5] # this is called slicing

array([1, 2, 3, 4])

In [51]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [52]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [53]:
arr[0:5] = 100 # this will broadcast the value. see the example

In [54]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [55]:
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
slice_of_arr = arr[0:6]

In [58]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [59]:
slice_of_arr[:] = 99

In [60]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
arr_copy = arr.copy()

In [63]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [65]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
arr_2d[0][0] # first represent the row and 2nd represent the column.

5

In [67]:
arr_2d[0]

array([ 5, 10, 15])

In [68]:
arr_2d[1][1]

25

In [69]:
arr_2d[2][1]

40

In [72]:
arr_2d[2,1] # here comma replaces the double bracket notation to single bracket notation

40

In [73]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [74]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [75]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

    CONDITIONAL SELECTION

In [76]:
arr = np.arange(1,11)

In [77]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [79]:
bool_arr = arr > 5

In [80]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [81]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [82]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [83]:
arr[arr<3]

array([1, 2])

In [85]:
arr_2d = np.arange(50).reshape(5,10)

In [86]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [96]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [97]:
arr = np.arange(0,11)

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [101]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [102]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [103]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [104]:
arr / arr

E:\Anaconda3.5\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [105]:
1 / arr # inf means infinity

E:\Anaconda3.5\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [106]:
arr ** arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [107]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [108]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [110]:
np.max(arr)

10

In [111]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [112]:
np.log(arr)

E:\Anaconda3.5\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

FOR UNIVERSAL ARRAY FUNCTION --- docs.scipy.org/doc/numpy/reference/ufuncs.html

In [114]:
np.sum(arr)

55

#  NUMPY EXERCISE

In [115]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [116]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [122]:
fives = np.ones(10)
fives[0:11] = 5
fives

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [123]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [124]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [125]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [130]:
np.random.rand(1)

array([ 0.86639909])

In [132]:
np.random.randn(25)

array([-0.55857998, -0.02697569, -0.91126837, -0.62697973,  1.26736379,
       -0.9455995 , -0.59932617,  0.63908819, -0.44441602, -1.50443159,
       -0.06565537,  0.80413273,  0.42258349,  0.06558148,  0.43146078,
        0.17298754, -1.53853245,  0.24676148, -0.14296505, -0.82449768,
        0.02522944,  0.63616433, -0.11710533,  0.57477046,  2.28203064])

In [137]:
np.linspace(0.01,1,100).reshape(10,10)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [138]:
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [139]:
num = np.arange(1,26).reshape(5,5)
num

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [142]:
num[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [143]:
num[3,4]

20

In [147]:
num[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [148]:
num[4:5]

array([[21, 22, 23, 24, 25]])

In [149]:
num[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [150]:
np.sum(num)

325

In [151]:
np.std(num)

7.2111025509279782

In [153]:
num.sum(axis=0)

array([55, 60, 65, 70, 75])